/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab1;

public class Library {
	
	//step 1.5
	public static void main(String arg[]) {
		//step 3.1
		Library lib = new Library();
		if(lib.someLibraryMethod())
		System.out.println("Hello, World!");
	}
	
	
    public boolean someLibraryMethod() {
        return true;
    }
}
